#!/usr/bin/env python3
"""
NOVA Agentic Research MVP
=========================

A runnable agent runtime with an honest, bounded scope:

    Evidence-backed web research and report generation.

Public interface:

    agent = AgenticAI(name="NOVA-Agent")

    if agent.plan("research current quantum-computing error correction"):
        success = agent.execute()
        print(agent.last_report.final_output)

Optional production integrations:

    NOVA_LLM_API_KEY
    NOVA_LLM_BASE_URL
    NOVA_LLM_MODEL
    TAVILY_API_KEY

Examples:

    OpenAI:
        NOVA_LLM_API_KEY=sk-...
        NOVA_LLM_BASE_URL=https://api.openai.com/v1
        NOVA_LLM_MODEL=gpt-4.1-mini

    NVIDIA NIM:
        NOVA_LLM_API_KEY=nvapi-...
        NOVA_LLM_BASE_URL=https://integrate.api.nvidia.com/v1
        NOVA_LLM_MODEL=moonshotai/kimi-k2-instruct

When Tavily is unavailable, the runtime attempts DuckDuckGo HTML search.

When an LLM is unavailable, NOVA creates a source-grounded evidence digest
instead of falsely claiming to have synthesized or verified the evidence.

The runtime exposes operational events, not hidden chain-of-thought.
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as dt
import hashlib
import ipaddress
import json
import logging
import os
import random
import re
import socket
import sqlite3
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid

from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from enum import Enum
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Callable, Iterable, Mapping, Optional


LOGGER = logging.getLogger("nova_agentic_mvp")
JSONValue = Any


# =============================================================================
# CORE MODELS
# =============================================================================


class Status(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"
    BLOCKED = "blocked"


@dataclass(slots=True)
class ToolResult:
    """
    Standard result envelope returned by every tool.

    ok:
        Whether the tool successfully completed its operation.

    data:
        The real output produced by the tool.

    confidence:
        Evidence-coverage heuristic. This is not a declaration of factual truth.

    evidence:
        Evidence records generated by the tool.

    error:
        Explicit failure reason.

    retryable:
        Whether retrying the same operation may reasonably succeed.

    metadata:
        Additional machine-readable execution information.
    """

    ok: bool
    data: JSONValue = None
    confidence: float = 0.0
    evidence: list[dict[str, Any]] = field(default_factory=list)
    error: Optional[str] = None
    retryable: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def success(
        cls,
        data: JSONValue,
        *,
        confidence: float = 1.0,
        evidence: Optional[list[dict[str, Any]]] = None,
        metadata: Optional[dict[str, Any]] = None,
    ) -> "ToolResult":
        return cls(
            ok=True,
            data=data,
            confidence=max(0.0, min(1.0, float(confidence))),
            evidence=evidence or [],
            metadata=metadata or {},
        )

    @classmethod
    def failure(
        cls,
        error: str,
        *,
        retryable: bool = False,
        metadata: Optional[dict[str, Any]] = None,
    ) -> "ToolResult":
        return cls(
            ok=False,
            error=error,
            retryable=retryable,
            metadata=metadata or {},
        )


@dataclass(slots=True)
class Step:
    id: str
    description: str
    tool: str
    args: dict[str, Any]

    depends_on: list[str] = field(default_factory=list)

    status: Status = Status.PENDING
    result: Optional[ToolResult] = None

    attempts: int = 0
    max_retries: int = 2

    is_final: bool = False

    started_at: Optional[float] = None
    ended_at: Optional[float] = None


@dataclass(slots=True)
class RunReport:
    run_id: str
    goal: str

    success: bool
    health: str

    final_output: str

    started_at: str
    ended_at: str
    elapsed_seconds: float

    steps: list[dict[str, Any]]
    events: list[dict[str, Any]]
    evidence: list[dict[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


@dataclass(slots=True)
class ToolContext:
    run_id: str
    goal: str

    memory: "SQLiteMemory"
    llm: "OpenAICompatibleClient"

    emit: Callable[
        [str, str, Optional[dict[str, Any]]],
        None,
    ]


ToolCallable = Callable[
    [dict[str, Any], ToolContext],
    ToolResult,
]


# =============================================================================
# PERSISTENT MEMORY
# =============================================================================


class SQLiteMemory:
    """
    Thread-safe, cross-run memory using SQLite.

    Stores complete JSON payloads rather than fake summaries.
    """

    def __init__(
        self,
        path: str | Path = ".nova_memory.sqlite3",
    ) -> None:
        self.path = str(path)
        self._lock = threading.RLock()

        self._conn = sqlite3.connect(
            self.path,
            check_same_thread=False,
        )

        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA synchronous=NORMAL")

        self._conn.execute(
            """
            CREATE TABLE IF NOT EXISTS episodes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                run_id TEXT NOT NULL,
                key TEXT NOT NULL,
                value_json TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )

        self._conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_episodes_key
            ON episodes(key)
            """
        )

        self._conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_episodes_run_id
            ON episodes(run_id)
            """
        )

        self._conn.commit()

    def store(
        self,
        run_id: str,
        key: str,
        value: Any,
    ) -> int:
        payload = json.dumps(
            value,
            ensure_ascii=False,
            default=str,
        )

        created_at = dt.datetime.now(
            dt.timezone.utc
        ).isoformat()

        with self._lock:
            cursor = self._conn.execute(
                """
                INSERT INTO episodes (
                    run_id,
                    key,
                    value_json,
                    created_at
                )
                VALUES (?, ?, ?, ?)
                """,
                (
                    run_id,
                    key,
                    payload,
                    created_at,
                ),
            )

            self._conn.commit()

            return int(cursor.lastrowid)

    def recall_latest(
        self,
        key: str,
        default: Any = None,
    ) -> Any:
        with self._lock:
            row = self._conn.execute(
                """
                SELECT value_json
                FROM episodes
                WHERE key = ?
                ORDER BY id DESC
                LIMIT 1
                """,
                (key,),
            ).fetchone()

        if not row:
            return default

        try:
            return json.loads(row[0])
        except json.JSONDecodeError:
            return default

    def search(
        self,
        keyword: str,
        limit: int = 20,
    ) -> list[dict[str, Any]]:
        pattern = f"%{keyword}%"

        with self._lock:
            rows = self._conn.execute(
                """
                SELECT
                    id,
                    run_id,
                    key,
                    value_json,
                    created_at
                FROM episodes
                WHERE key LIKE ?
                   OR value_json LIKE ?
                ORDER BY id DESC
                LIMIT ?
                """,
                (
                    pattern,
                    pattern,
                    max(1, limit),
                ),
            ).fetchall()

        results: list[dict[str, Any]] = []

        for row in rows:
            try:
                value = json.loads(row[3])
            except json.JSONDecodeError:
                value = row[3]

            results.append(
                {
                    "id": row[0],
                    "run_id": row[1],
                    "key": row[2],
                    "value": value,
                    "created_at": row[4],
                }
            )

        return results

    def close(self) -> None:
        with self._lock:
            self._conn.close()


# =============================================================================
# HTTP UTILITIES
# =============================================================================


def _json_request(
    url: str,
    *,
    method: str = "GET",
    headers: Optional[Mapping[str, str]] = None,
    payload: Optional[dict[str, Any]] = None,
    timeout: float = 25.0,
) -> Any:
    body: Optional[bytes] = None

    final_headers = {
        "User-Agent": (
            "NOVA-Agentic-MVP/1.0 "
            "(evidence-oriented research runtime)"
        ),
        "Accept": "application/json",
    }

    if headers:
        final_headers.update(headers)

    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        final_headers.setdefault(
            "Content-Type",
            "application/json",
        )

    request = urllib.request.Request(
        url=url,
        data=body,
        headers=final_headers,
        method=method,
    )

    with urllib.request.urlopen(
        request,
        timeout=timeout,
    ) as response:
        raw = response.read()

    return json.loads(raw.decode("utf-8"))


def _text_request(
    url: str,
    *,
    timeout: float = 20.0,
    max_bytes: int = 2_000_000,
) -> tuple[str, str]:
    request = urllib.request.Request(
        url=url,
        headers={
            "User-Agent": (
                "Mozilla/5.0 "
                "(compatible; NOVA-Agentic-MVP/1.0)"
            ),
            "Accept": (
                "text/html,"
                "application/xhtml+xml,"
                "text/plain;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        method="GET",
    )

    with urllib.request.urlopen(
        request,
        timeout=timeout,
    ) as response:
        content_type = response.headers.get_content_type()
        charset = (
            response.headers.get_content_charset()
            or "utf-8"
        )
        raw = response.read(max_bytes)

    return (
        raw.decode(
            charset,
            errors="replace",
        ),
        content_type,
    )


# =============================================================================
# OPENAI-COMPATIBLE LLM CLIENT
# =============================================================================


class OpenAICompatibleClient:
    """
    Supports OpenAI-compatible chat-completions providers.

    Environment variables:

        NOVA_LLM_API_KEY
        NOVA_LLM_BASE_URL
        NOVA_LLM_MODEL

    OPENAI_* variables are accepted as fallbacks.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: float = 60.0,
    ) -> None:
        self.api_key = (
            api_key
            or os.getenv("NOVA_LLM_API_KEY")
            or os.getenv("OPENAI_API_KEY")
        )

        self.base_url = (
            base_url
            or os.getenv("NOVA_LLM_BASE_URL")
            or os.getenv("OPENAI_BASE_URL")
            or "https://api.openai.com/v1"
        ).rstrip("/")

        self.model = (
            model
            or os.getenv("NOVA_LLM_MODEL")
            or os.getenv("OPENAI_MODEL")
            or "gpt-4.1-mini"
        )

        self.timeout = timeout

    @property
    def configured(self) -> bool:
        return bool(
            self.api_key
            and self.model
            and self.base_url
        )

    def complete(
        self,
        *,
        system: str,
        user: str,
        temperature: float = 0.1,
        max_tokens: int = 2500,
        json_mode: bool = False,
    ) -> str:
        if not self.configured:
            raise RuntimeError(
                "LLM is not configured"
            )

        payload: dict[str, Any] = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": system,
                },
                {
                    "role": "user",
                    "content": user,
                },
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        if json_mode:
            payload["response_format"] = {
                "type": "json_object"
            }

        response = _json_request(
            f"{self.base_url}/chat/completions",
            method="POST",
            headers={
                "Authorization": (
                    f"Bearer {self.api_key}"
                )
            },
            payload=payload,
            timeout=self.timeout,
        )

        choices = response.get("choices") or []

        if not choices:
            raise RuntimeError(
                "LLM response contained no choices"
            )

        content = (
            choices[0]
            .get("message", {})
            .get("content")
        )

        if not isinstance(content, str):
            raise RuntimeError(
                "LLM response contained invalid content"
            )

        content = content.strip()

        if not content:
            raise RuntimeError(
                "LLM response contained empty content"
            )

        return content


# =============================================================================
# DUCKDUCKGO RESULT PARSER
# =============================================================================


class _DDGParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(
            convert_charrefs=True
        )

        self.results: list[dict[str, str]] = []

        self._in_title = False
        self._in_snippet = False

        self._current_title: list[str] = []
        self._current_snippet: list[str] = []
        self._current_url: Optional[str] = None

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, Optional[str]]],
    ) -> None:
        attributes = dict(attrs)

        classes = set(
            (attributes.get("class") or "").split()
        )

        if tag == "a" and "result__a" in classes:
            self._flush()

            self._in_title = True
            self._current_url = attributes.get("href")

        elif (
            tag in {"a", "div"}
            and "result__snippet" in classes
        ):
            self._in_snippet = True

    def handle_endtag(
        self,
        tag: str,
    ) -> None:
        if tag == "a" and self._in_title:
            self._in_title = False

        if (
            tag in {"a", "div"}
            and self._in_snippet
        ):
            self._in_snippet = False

    def handle_data(
        self,
        data: str,
    ) -> None:
        if self._in_title:
            self._current_title.append(data)

        if self._in_snippet:
            self._current_snippet.append(data)

    def close(self) -> None:
        super().close()
        self._flush()

    def _flush(self) -> None:
        if (
            self._current_url
            and self._current_title
        ):
            url = _unwrap_ddg_url(
                self._current_url
            )

            self.results.append(
                {
                    "title": " ".join(
                        self._current_title
                    ).strip(),
                    "url": url,
                    "snippet": " ".join(
                        self._current_snippet
                    ).strip(),
                }
            )

        self._current_title = []
        self._current_snippet = []
        self._current_url = None


def _unwrap_ddg_url(
    url: str,
) -> str:
    parsed = urllib.parse.urlparse(url)
    query = urllib.parse.parse_qs(
        parsed.query
    )

    if "uddg" in query and query["uddg"]:
        return urllib.parse.unquote(
            query["uddg"][0]
        )

    if url.startswith("//"):
        return "https:" + url

    return url


# =============================================================================
# HTML TEXT EXTRACTION
# =============================================================================


class _TextExtractor(HTMLParser):
    SKIP_TAGS = {
        "script",
        "style",
        "noscript",
        "svg",
        "canvas",
    }

    def __init__(self) -> None:
        super().__init__(
            convert_charrefs=True
        )

        self._skip_depth = 0
        self._in_title = False

        self.parts: list[str] = []
        self.title: list[str] = []

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, Optional[str]]],
    ) -> None:
        del attrs

        if tag in self.SKIP_TAGS:
            self._skip_depth += 1

        elif tag == "title":
            self._in_title = True

    def handle_endtag(
        self,
        tag: str,
    ) -> None:
        if (
            tag in self.SKIP_TAGS
            and self._skip_depth
        ):
            self._skip_depth -= 1

        elif tag == "title":
            self._in_title = False

    def handle_data(
        self,
        data: str,
    ) -> None:
        if self._skip_depth:
            return

        cleaned = " ".join(
            data.split()
        )

        if not cleaned:
            return

        if self._in_title:
            self.title.append(cleaned)

        self.parts.append(cleaned)


# =============================================================================
# URL SAFETY
# =============================================================================


def _is_public_http_url(
    url: str,
) -> bool:
    """
    Blocks localhost, private networks, link-local networks and malformed URLs.

    This limits basic SSRF exposure when the agent fetches search results.
    """

    try:
        parsed = urllib.parse.urlparse(url)

        if parsed.scheme not in {
            "http",
            "https",
        }:
            return False

        if not parsed.hostname:
            return False

        host = parsed.hostname.lower()

        if host in {
            "localhost",
            "localhost.localdomain",
        }:
            return False

        if host.endswith(".local"):
            return False

        try:
            addresses = socket.getaddrinfo(
                host,
                parsed.port or (
                    443
                    if parsed.scheme == "https"
                    else 80
                ),
                type=socket.SOCK_STREAM,
            )
        except socket.gaierror:
            return False

        for address in addresses:
            raw_ip = address[4][0]
            ip = ipaddress.ip_address(raw_ip)

            if not ip.is_global:
                return False

        return True

    except (
        ValueError,
        OSError,
    ):
        return False


# =============================================================================
# SEARCH PROVIDERS
# =============================================================================


def _normalize_sources(
    items: Iterable[dict[str, Any]],
) -> list[dict[str, Any]]:
    seen: set[str] = set()
    output: list[dict[str, Any]] = []

    for item in items:
        url = str(
            item.get("url") or ""
        ).strip()

        if not url:
            continue

        if url in seen:
            continue

        seen.add(url)

        output.append(
            {
                "title": str(
                    item.get("title")
                    or url
                ).strip(),
                "url": url,
                "snippet": str(
                    item.get("snippet")
                    or item.get("content")
                    or ""
                ).strip(),
                "provider_score": item.get("score"),
            }
        )

    return output


def _search_tavily(
    query: str,
    max_results: int,
) -> list[dict[str, Any]]:
    api_key = os.getenv(
        "TAVILY_API_KEY"
    )

    if not api_key:
        raise RuntimeError(
            "TAVILY_API_KEY is not configured"
        )

    response = _json_request(
        "https://api.tavily.com/search",
        method="POST",
        payload={
            "api_key": api_key,
            "query": query,
            "search_depth": "advanced",
            "max_results": max_results,
            "include_answer": False,
            "include_raw_content": False,
        },
        timeout=30.0,
    )

    return _normalize_sources(
        response.get("results") or []
    )


def _search_duckduckgo(
    query: str,
    max_results: int,
) -> list[dict[str, Any]]:
    encoded = urllib.parse.urlencode(
        {"q": query}
    )

    body, _content_type = _text_request(
        (
            "https://html.duckduckgo.com/"
            f"html/?{encoded}"
        ),
        timeout=25.0,
    )

    parser = _DDGParser()
    parser.feed(body)
    parser.close()

    return _normalize_sources(
        parser.results[:max_results]
    )


# =============================================================================
# TOOL IMPLEMENTATIONS
# =============================================================================


def _confidence_from_evidence(
    source_count: int,
    page_count: int = 0,
) -> float:
    """
    Transparent evidence-coverage heuristic.

    It does not claim the answer is factually true.
    """

    return min(
        0.95,
        (
            0.30
            + min(source_count, 8) * 0.06
            + min(page_count, 5) * 0.04
        ),
    )


def tool_web_research(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    del ctx

    queries = args.get("queries")

    if isinstance(queries, str):
        queries = [queries]

    if (
        not isinstance(queries, list)
        or not all(
            isinstance(query, str)
            for query in queries
        )
    ):
        return ToolResult.failure(
            "'queries' must be a string "
            "or list of strings"
        )

    cleaned_queries = [
        query.strip()
        for query in queries
        if query.strip()
    ]

    if not cleaned_queries:
        return ToolResult.failure(
            "No valid search queries were supplied"
        )

    try:
        max_results = int(
            args.get("max_results", 6)
        )
    except (
        TypeError,
        ValueError,
    ):
        return ToolResult.failure(
            "'max_results' must be an integer"
        )

    max_results = max(
        1,
        min(max_results, 10),
    )

    provider = (
        "tavily"
        if os.getenv("TAVILY_API_KEY")
        else "duckduckgo"
    )

    all_sources: list[dict[str, Any]] = []
    errors: list[str] = []

    for query in cleaned_queries:
        try:
            if provider == "tavily":
                sources = _search_tavily(
                    query,
                    max_results,
                )
            else:
                sources = _search_duckduckgo(
                    query,
                    max_results,
                )

            for source in sources:
                source["query"] = query
                source["provider"] = provider

            all_sources.extend(sources)

        except (
            urllib.error.URLError,
            TimeoutError,
            RuntimeError,
            ValueError,
        ) as exc:
            errors.append(
                f"{query}: {exc}"
            )

    unique = _normalize_sources(
        all_sources
    )

    if not unique:
        return ToolResult.failure(
            (
                "All web searches failed or "
                "returned zero results. "
                + "; ".join(errors)
            ),
            retryable=True,
            metadata={
                "provider": provider,
                "queries": cleaned_queries,
            },
        )

    data = {
        "queries": cleaned_queries,
        "provider": provider,
        "sources": unique,
        "partial_errors": errors,
        "retrieved_at": dt.datetime.now(
            dt.timezone.utc
        ).isoformat(),
    }

    evidence = [
        {
            "type": "search_result",
            "title": source["title"],
            "url": source["url"],
        }
        for source in unique
    ]

    return ToolResult.success(
        data,
        confidence=_confidence_from_evidence(
            len(unique)
        ),
        evidence=evidence,
        metadata={
            "partial": bool(errors),
            "provider": provider,
        },
    )


def tool_fetch_sources(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    del ctx

    research = args.get("research")

    if not isinstance(research, dict):
        return ToolResult.failure(
            "'research' must contain "
            "web_research output"
        )

    sources = research.get("sources") or []

    if (
        not isinstance(sources, list)
        or not sources
    ):
        return ToolResult.failure(
            "No sources were supplied for fetching"
        )

    try:
        max_pages = int(
            args.get("max_pages", 4)
        )
    except (
        TypeError,
        ValueError,
    ):
        return ToolResult.failure(
            "'max_pages' must be an integer"
        )

    max_pages = max(
        1,
        min(max_pages, 8),
    )

    selected = sources[:max_pages]

    def fetch_one(
        source: dict[str, Any],
    ) -> tuple[
        Optional[dict[str, Any]],
        Optional[str],
    ]:
        url = str(
            source.get("url") or ""
        )

        if not _is_public_http_url(url):
            return (
                None,
                (
                    "Rejected non-public "
                    f"or invalid URL: {url}"
                ),
            )

        try:
            body, content_type = _text_request(
                url,
                timeout=20.0,
            )

            if content_type in {
                "text/html",
                "application/xhtml+xml",
            }:
                parser = _TextExtractor()
                parser.feed(body)
                parser.close()

                text = "\n".join(
                    parser.parts
                )

                title = (
                    " ".join(parser.title).strip()
                    or source.get("title")
                    or url
                )

            else:
                text = body
                title = (
                    source.get("title")
                    or url
                )

            text = re.sub(
                r"\n{3,}",
                "\n\n",
                text,
            ).strip()

            if len(text) < 120:
                return (
                    None,
                    (
                        "Insufficient readable "
                        f"content from {url}"
                    ),
                )

            digest = hashlib.sha256(
                text.encode("utf-8")
            ).hexdigest()

            return (
                {
                    "title": str(title),
                    "url": url,
                    "text": text[:12_000],
                    "content_type": content_type,
                    "sha256": digest,
                },
                None,
            )

        except (
            urllib.error.URLError,
            TimeoutError,
            ValueError,
            OSError,
        ) as exc:
            return (
                None,
                f"{url}: {exc}",
            )

    pages: list[dict[str, Any]] = []
    errors: list[str] = []

    worker_count = min(
        4,
        len(selected),
    )

    with ThreadPoolExecutor(
        max_workers=worker_count
    ) as pool:
        future_map = {
            pool.submit(
                fetch_one,
                source,
            ): source
            for source in selected
        }

        for future in as_completed(
            future_map
        ):
            try:
                page, error = future.result()
            except Exception as exc:
                page = None
                error = (
                    "Unhandled fetch worker error: "
                    f"{type(exc).__name__}: {exc}"
                )

            if page:
                pages.append(page)

            if error:
                errors.append(error)

    if not pages:
        return ToolResult.success(
            {
                "pages": [],
                "errors": errors,
                "used_search_snippets_only": True,
            },
            confidence=_confidence_from_evidence(
                len(sources),
                0,
            ),
            evidence=[],
            metadata={
                "partial": True,
                "fetched_pages": 0,
            },
        )

    evidence = [
        {
            "type": "fetched_page",
            "title": page["title"],
            "url": page["url"],
            "sha256": page["sha256"],
        }
        for page in pages
    ]

    return ToolResult.success(
        {
            "pages": pages,
            "errors": errors,
            "used_search_snippets_only": False,
        },
        confidence=_confidence_from_evidence(
            len(sources),
            len(pages),
        ),
        evidence=evidence,
        metadata={
            "partial": bool(errors),
            "fetched_pages": len(pages),
        },
    )


def _build_evidence_packet(
    research: dict[str, Any],
    fetched: dict[str, Any],
    max_chars: int = 45_000,
) -> tuple[
    str,
    list[dict[str, Any]],
]:
    sources = research.get("sources") or []

    pages_by_url = {
        page.get("url"): page
        for page in (
            fetched.get("pages") or []
        )
        if page.get("url")
    }

    normalized: list[dict[str, Any]] = []
    remaining = max_chars

    for index, source in enumerate(
        sources,
        start=1,
    ):
        page = pages_by_url.get(
            source.get("url")
        )

        content = (
            (page or {}).get("text")
            or source.get("snippet")
            or ""
        )

        maximum_for_source = min(
            8_000,
            remaining,
        )

        content = str(content)[
            :maximum_for_source
        ]

        remaining -= len(content)

        normalized.append(
            {
                "id": index,
                "title": source.get("title"),
                "url": source.get("url"),
                "content": content,
            }
        )

        if remaining <= 0:
            break

    encoded = json.dumps(
        normalized,
        ensure_ascii=False,
        indent=2,
    )

    return encoded, normalized


def _fallback_evidence_digest(
    goal: str,
    sources: list[dict[str, Any]],
) -> str:
    lines = [
        f"# Evidence Digest: {goal}",
        "",
        (
            "> An LLM was not configured. "
            "This is a source-grounded evidence "
            "index, not an AI-generated synthesis."
        ),
        "",
        "## Retrieved evidence",
        "",
    ]

    for source in sources:
        snippet = re.sub(
            r"\s+",
            " ",
            str(
                source.get("content")
                or ""
            ),
        ).strip()

        if len(snippet) > 600:
            snippet = (
                snippet[:597]
                + "..."
            )

        lines.extend(
            [
                (
                    f"### [{source['id']}] "
                    f"{source.get('title') or source.get('url')}"
                ),
                (
                    snippet
                    or "No readable excerpt was available."
                ),
                (
                    "Source: "
                    f"{source.get('url')}"
                ),
                "",
            ]
        )

    lines.extend(
        [
            "## Limitations",
            "",
            (
                "No model-based synthesis or semantic "
                "claim verification was performed. "
                "Review the linked sources before "
                "relying on this digest."
            ),
        ]
    )

    return "\n".join(lines).strip()


def tool_synthesize_report(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    goal = str(
        args.get("goal")
        or ctx.goal
    ).strip()

    research = args.get("research")
    fetched = args.get("fetched")

    if not isinstance(research, dict):
        return ToolResult.failure(
            "Missing or invalid research evidence"
        )

    if not isinstance(fetched, dict):
        return ToolResult.failure(
            "Missing or invalid fetched evidence"
        )

    evidence_json, sources = (
        _build_evidence_packet(
            research,
            fetched,
        )
    )

    if not sources:
        return ToolResult.failure(
            "No evidence was available for synthesis"
        )

    page_count = len(
        fetched.get("pages") or []
    )

    confidence = _confidence_from_evidence(
        len(sources),
        page_count,
    )

    source_evidence = [
        {
            "type": "source",
            "title": source["title"],
            "url": source["url"],
        }
        for source in sources
    ]

    if not ctx.llm.configured:
        digest = _fallback_evidence_digest(
            goal,
            sources,
        )

        return ToolResult.success(
            digest,
            confidence=confidence,
            evidence=source_evidence,
            metadata={
                "mode": "evidence_digest",
                "llm_used": False,
            },
        )

    system_prompt = (
        "You are an evidence-bound research analyst. "
        "Use only the supplied evidence. "
        "Never invent statistics, dates, entities, "
        "quotations, sources, results, or conclusions. "
        "Mark uncertainty explicitly. "
        "Cite every material factual claim with "
        "bracketed source IDs such as [1]. "
        "Do not cite a source unless the source "
        "actually supports the claim. "
        "Finish with a Sources section containing "
        "the source title and URL for every cited source."
    )

    user_prompt = (
        f"Research objective:\n{goal}\n\n"
        "Write a concise but substantive report with:\n"
        "1. Executive Summary\n"
        "2. Key Findings\n"
        "3. Evidence and Analysis\n"
        "4. Risks and Uncertainties\n"
        "5. Sources\n\n"
        f"Evidence packet:\n{evidence_json}"
    )

    try:
        text = ctx.llm.complete(
            system=system_prompt,
            user=user_prompt,
            temperature=0.1,
            max_tokens=3200,
        )

    except (
        RuntimeError,
        urllib.error.URLError,
        TimeoutError,
        ValueError,
    ) as exc:
        return ToolResult.failure(
            f"LLM synthesis failed: {exc}",
            retryable=True,
        )

    return ToolResult.success(
        text,
        confidence=confidence,
        evidence=source_evidence,
        metadata={
            "mode": "llm_synthesis",
            "llm_used": True,
            "model": ctx.llm.model,
        },
    )


# =============================================================================
# REPORT VERIFICATION
# =============================================================================


def _deterministic_report_checks(
    report: str,
    sources: list[dict[str, Any]],
    *,
    llm_used: bool,
) -> dict[str, Any]:
    issues: list[str] = []

    if len(report.strip()) < 350:
        issues.append(
            "Report is too short to be useful"
        )

    unresolved_patterns = [
        "__S",
        "__R",
        "${",
    ]

    for pattern in unresolved_patterns:
        if pattern in report:
            issues.append(
                (
                    "Unresolved execution "
                    f"placeholder detected: {pattern}"
                )
            )

    if not sources:
        issues.append(
            "No sources were attached"
        )

    if llm_used:
        citations = {
            int(number)
            for number in re.findall(
                r"\[(\d+)\]",
                report,
            )
        }

        valid_ids = set(
            range(
                1,
                len(sources) + 1,
            )
        )

        if not citations:
            issues.append(
                "No bracketed evidence citations were found"
            )

        invalid = citations - valid_ids

        if invalid:
            issues.append(
                (
                    "Invalid citation IDs: "
                    f"{sorted(invalid)}"
                )
            )

        if "source" not in report.lower():
            issues.append(
                "Sources section is missing"
            )

    forbidden_markers = [
        "73 % of",
        "Adoption CAGR: 34 %",
        "source1.io",
        "previously indexed content",
        "3 key findings produced",
    ]

    for marker in forbidden_markers:
        if marker.lower() in report.lower():
            issues.append(
                (
                    "Known fabricated-demo marker "
                    f"detected: {marker!r}"
                )
            )

    return {
        "passed": not issues,
        "issues": issues,
    }


def _extract_json_object(
    text: str,
) -> dict[str, Any]:
    stripped = text.strip()

    if stripped.startswith("```"):
        stripped = re.sub(
            r"^```(?:json)?\s*",
            "",
            stripped,
        )

        stripped = re.sub(
            r"\s*```$",
            "",
            stripped,
        )

    try:
        parsed = json.loads(stripped)

    except json.JSONDecodeError:
        match = re.search(
            r"\{.*\}",
            stripped,
            re.DOTALL,
        )

        if not match:
            raise

        parsed = json.loads(
            match.group(0)
        )

    if not isinstance(parsed, dict):
        raise ValueError(
            "Expected a JSON object"
        )

    return parsed


def tool_verify_report(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    report = str(
        args.get("report") or ""
    )

    research = (
        args.get("research")
        or {}
    )

    fetched = (
        args.get("fetched")
        or {}
    )

    llm_used = bool(
        args.get("llm_used")
    )

    sources_json, sources = (
        _build_evidence_packet(
            research,
            fetched,
        )
    )

    checks = _deterministic_report_checks(
        report,
        sources,
        llm_used=llm_used,
    )

    semantic: dict[str, Any] = {
        "passed": True,
        "issues": [],
        "unsupported_claims": [],
        "mode": "not_run",
    }

    if ctx.llm.configured and llm_used:
        system_prompt = (
            "You are a strict evidence verifier. "
            "Compare the report against the evidence. "
            "Return JSON only with these keys: "
            "passed, issues, unsupported_claims. "
            "passed must be a boolean. "
            "issues and unsupported_claims must be arrays "
            "of strings. Fail the report when it contains "
            "a material claim unsupported by the supplied "
            "evidence or uses citations incorrectly."
        )

        user_prompt = (
            f"REPORT:\n{report}\n\n"
            f"EVIDENCE:\n{sources_json}"
        )

        try:
            raw = ctx.llm.complete(
                system=system_prompt,
                user=user_prompt,
                temperature=0.0,
                max_tokens=1200,
                json_mode=True,
            )

            semantic = _extract_json_object(raw)
            semantic["mode"] = "llm_verifier"

        except (
            RuntimeError,
            urllib.error.URLError,
            TimeoutError,
            ValueError,
            json.JSONDecodeError,
        ) as exc:
            semantic = {
                "passed": False,
                "issues": [
                    (
                        "Semantic verifier failed: "
                        f"{exc}"
                    )
                ],
                "unsupported_claims": [],
                "mode": "verifier_error",
            }

    semantic_issues = semantic.get(
        "issues",
        [],
    )

    if not isinstance(
        semantic_issues,
        list,
    ):
        semantic_issues = [
            str(semantic_issues)
        ]

    unsupported_claims = semantic.get(
        "unsupported_claims",
        [],
    )

    if not isinstance(
        unsupported_claims,
        list,
    ):
        unsupported_claims = [
            str(unsupported_claims)
        ]

    combined_issues = (
        list(checks["issues"])
        + [
            str(issue)
            for issue in semantic_issues
        ]
    )

    unsupported = [
        str(claim)
        for claim in unsupported_claims
    ]

    passed = bool(
        checks["passed"]
        and semantic.get(
            "passed",
            True,
        )
    )

    data = {
        "passed": passed,
        "issues": combined_issues,
        "unsupported_claims": unsupported,
        "deterministic_checks": checks,
        "semantic_verifier": semantic,
    }

    return ToolResult.success(
        data,
        confidence=(
            1.0
            if passed
            else 0.45
        ),
        metadata={
            "verification_passed": passed,
        },
    )


def tool_revise_report(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    goal = str(
        args.get("goal")
        or ctx.goal
    )

    report = str(
        args.get("report")
        or ""
    )

    verification = (
        args.get("verification")
        or {}
    )

    research = (
        args.get("research")
        or {}
    )

    fetched = (
        args.get("fetched")
        or {}
    )

    llm_used = bool(
        args.get("llm_used")
    )

    _evidence_json, sources = (
        _build_evidence_packet(
            research,
            fetched,
        )
    )

    page_count = len(
        fetched.get("pages") or []
    )

    confidence = _confidence_from_evidence(
        len(sources),
        page_count,
    )

    source_evidence = [
        {
            "type": "source",
            "title": source["title"],
            "url": source["url"],
        }
        for source in sources
    ]

    if verification.get("passed"):
        return ToolResult.success(
            report,
            confidence=confidence,
            evidence=source_evidence,
            metadata={
                "revised": False,
                "verification_passed": True,
            },
        )

    issues = [
        str(issue)
        for issue in verification.get(
            "issues",
            [],
        )
    ]

    unsupported = [
        str(claim)
        for claim in verification.get(
            "unsupported_claims",
            [],
        )
    ]

    if ctx.llm.configured and llm_used:
        evidence_json, _sources = (
            _build_evidence_packet(
                research,
                fetched,
            )
        )

        system_prompt = (
            "Revise an evidence-bound report. "
            "Remove or qualify unsupported claims, "
            "repair citations, and address every "
            "verifier issue. Use only supplied evidence. "
            "Never invent replacement facts. "
            "Return the complete revised report, "
            "not commentary about the revision."
        )

        verifier_payload = {
            "issues": issues,
            "unsupported_claims": unsupported,
        }

        user_prompt = (
            f"OBJECTIVE:\n{goal}\n\n"
            f"CURRENT REPORT:\n{report}\n\n"
            "VERIFIER ISSUES:\n"
            f"{json.dumps(verifier_payload, indent=2)}\n\n"
            f"EVIDENCE:\n{evidence_json}"
        )

        try:
            revised = ctx.llm.complete(
                system=system_prompt,
                user=user_prompt,
                temperature=0.05,
                max_tokens=3400,
            )

        except (
            RuntimeError,
            urllib.error.URLError,
            TimeoutError,
            ValueError,
        ) as exc:
            return ToolResult.failure(
                f"Report revision failed: {exc}",
                retryable=True,
            )

        final_checks = (
            _deterministic_report_checks(
                revised,
                sources,
                llm_used=True,
            )
        )

        if not final_checks["passed"]:
            return ToolResult.failure(
                (
                    "Revised report still failed "
                    "deterministic verification: "
                    + "; ".join(
                        final_checks["issues"]
                    )
                ),
                retryable=False,
                metadata={
                    "checks": final_checks,
                },
            )

        return ToolResult.success(
            revised,
            confidence=confidence,
            evidence=source_evidence,
            metadata={
                "revised": True,
                "verification_passed": True,
            },
        )

    appendix = [
        "",
        "## Verification status",
        "",
        (
            "The automated checks did not fully pass. "
            "No LLM was configured to perform a "
            "source-grounded semantic revision."
        ),
    ]

    if issues:
        appendix.extend(
            [
                "",
                "Issues:",
            ]
        )

        appendix.extend(
            f"- {issue}"
            for issue in issues
        )

    final = (
        report.rstrip()
        + "\n"
        + "\n".join(appendix)
    )

    return ToolResult.success(
        final,
        confidence=min(
            0.65,
            confidence,
        ),
        evidence=source_evidence,
        metadata={
            "revised": False,
            "verification_passed": False,
            "llm_used": False,
        },
    )


def tool_persist_result(
    args: dict[str, Any],
    ctx: ToolContext,
) -> ToolResult:
    key = str(
        args.get("key")
        or "final_report"
    )

    value = args.get("value")

    record_id = ctx.memory.store(
        ctx.run_id,
        key,
        value,
    )

    return ToolResult.success(
        {
            "record_id": record_id,
            "key": key,
        },
        confidence=1.0,
        metadata={
            "persistent": True,
        },
    )


def default_tool_registry() -> dict[
    str,
    ToolCallable,
]:
    return {
        "web_research": tool_web_research,
        "fetch_sources": tool_fetch_sources,
        "synthesize_report": tool_synthesize_report,
        "verify_report": tool_verify_report,
        "revise_report": tool_revise_report,
        "persist_result": tool_persist_result,
    }


# =============================================================================
# PLAN VALIDATION
# =============================================================================


class PlanValidationError(ValueError):
    pass


# =============================================================================
# AGENTIC RUNTIME
# =============================================================================


class AgenticAI:
    """
    Evidence-oriented research agent.

    Interface:

        agent.plan(objective)
        agent.execute()

    The runtime executes a dependency graph, retries explicitly retryable
    operations, blocks steps whose dependencies fail, verifies the final report,
    persists execution evidence, and returns failure honestly.
    """

    def __init__(
        self,
        name: str = "NOVA-Agent",
        *,
        memory_path: str | Path = ".nova_memory.sqlite3",
        max_parallel: int = 4,
        tools: Optional[
            dict[str, ToolCallable]
        ] = None,
        llm: Optional[
            OpenAICompatibleClient
        ] = None,
        retry_base_seconds: float = 0.75,
    ) -> None:
        self.name = name

        self.max_parallel = max(
            1,
            int(max_parallel),
        )

        self.retry_base_seconds = max(
            0.0,
            float(retry_base_seconds),
        )

        self.memory = SQLiteMemory(
            memory_path
        )

        self.llm = (
            llm
            or OpenAICompatibleClient()
        )

        self.tools = default_tool_registry()

        if tools:
            self.tools.update(tools)

        self.goal: Optional[str] = None
        self.plan_steps: list[Step] = []

        self.last_report: Optional[
            RunReport
        ] = None

        self._run_id = ""
        self._results: dict[str, Any] = {}
        self._events: list[
            dict[str, Any]
        ] = []

        self._lock = threading.RLock()

    def close(self) -> None:
        self.memory.close()

    def __enter__(self) -> "AgenticAI":
        return self

    def __exit__(
        self,
        exc_type: Any,
        exc: Any,
        traceback: Any,
    ) -> None:
        del exc_type
        del exc
        del traceback

        self.close()

    def _emit(
        self,
        event: str,
        message: str,
        details: Optional[
            dict[str, Any]
        ] = None,
    ) -> None:
        item = {
            "ts": dt.datetime.now(
                dt.timezone.utc
            ).isoformat(),
            "event": event,
            "message": message,
            "details": details or {},
        }

        with self._lock:
            self._events.append(item)

        LOGGER.info(
            "%s: %s",
            event,
            message,
        )

    def plan(
        self,
        objective: str,
    ) -> bool:
        objective = str(
            objective or ""
        ).strip()

        if not objective:
            raise ValueError(
                "objective must not be empty"
            )

        self.goal = objective

        current_year = dt.datetime.now(
            dt.timezone.utc
        ).year

        safe_key = re.sub(
            r"[^a-zA-Z0-9_.-]+",
            "_",
            objective.lower(),
        ).strip("_")[:80]

        self.plan_steps = [
            Step(
                id="R1",
                description=(
                    "Gather current web evidence"
                ),
                tool="web_research",
                args={
                    "queries": [
                        objective,
                        (
                            f"{objective} "
                            "latest developments "
                            f"{current_year}"
                        ),
                    ],
                    "max_results": 6,
                },
                max_retries=2,
            ),
            Step(
                id="R2",
                description=(
                    "Fetch and extract "
                    "the strongest sources"
                ),
                tool="fetch_sources",
                args={
                    "research": "__R1__",
                    "max_pages": 4,
                },
                depends_on=["R1"],
                max_retries=1,
            ),
            Step(
                id="R3",
                description=(
                    "Create a source-grounded report"
                ),
                tool="synthesize_report",
                args={
                    "goal": objective,
                    "research": "__R1__",
                    "fetched": "__R2__",
                },
                depends_on=[
                    "R1",
                    "R2",
                ],
                max_retries=2,
            ),
            Step(
                id="R4",
                description=(
                    "Verify citations, completeness, "
                    "and evidence grounding"
                ),
                tool="verify_report",
                args={
                    "report": "__R3__",
                    "research": "__R1__",
                    "fetched": "__R2__",
                    "llm_used": self.llm.configured,
                },
                depends_on=[
                    "R1",
                    "R2",
                    "R3",
                ],
                max_retries=0,
            ),
            Step(
                id="R5",
                description=(
                    "Finalize or revise "
                    "the verified report"
                ),
                tool="revise_report",
                args={
                    "goal": objective,
                    "report": "__R3__",
                    "verification": "__R4__",
                    "research": "__R1__",
                    "fetched": "__R2__",
                    "llm_used": self.llm.configured,
                },
                depends_on=[
                    "R1",
                    "R2",
                    "R3",
                    "R4",
                ],
                max_retries=1,
                is_final=True,
            ),
            Step(
                id="R6",
                description=(
                    "Persist the final report"
                ),
                tool="persist_result",
                args={
                    "key": (
                        "research_report_"
                        f"{safe_key}"
                    ),
                    "value": "__R5__",
                },
                depends_on=["R5"],
                max_retries=1,
            ),
        ]

        self.validate_plan()

        return True

    def validate_plan(self) -> None:
        if not self.plan_steps:
            raise PlanValidationError(
                "Plan has no steps"
            )

        ids = [
            step.id
            for step in self.plan_steps
        ]

        if len(ids) != len(set(ids)):
            raise PlanValidationError(
                "Step IDs must be unique"
            )

        by_id = {
            step.id: step
            for step in self.plan_steps
        }

        final_steps = [
            step
            for step in self.plan_steps
            if step.is_final
        ]

        if len(final_steps) != 1:
            raise PlanValidationError(
                (
                    "Plan must contain exactly "
                    "one final step"
                )
            )

        for step in self.plan_steps:
            if step.tool not in self.tools:
                raise PlanValidationError(
                    (
                        f"Step {step.id} references "
                        f"unknown tool {step.tool!r}"
                    )
                )

            if step.id in step.depends_on:
                raise PlanValidationError(
                    (
                        f"Step {step.id} "
                        "depends on itself"
                    )
                )

            missing = [
                dependency
                for dependency in step.depends_on
                if dependency not in by_id
            ]

            if missing:
                raise PlanValidationError(
                    (
                        f"Step {step.id} has missing "
                        f"dependencies: {missing}"
                    )
                )

        visiting: set[str] = set()
        visited: set[str] = set()

        def visit(
            step_id: str,
        ) -> None:
            if step_id in visiting:
                raise PlanValidationError(
                    (
                        "Dependency cycle "
                        f"detected at {step_id}"
                    )
                )

            if step_id in visited:
                return

            visiting.add(step_id)

            for dependency in (
                by_id[step_id].depends_on
            ):
                visit(dependency)

            visiting.remove(step_id)
            visited.add(step_id)

        for step_id in ids:
            visit(step_id)

    def _resolve_value(
        self,
        value: Any,
    ) -> Any:
        if isinstance(value, str):
            match = re.fullmatch(
                r"__(.+)__",
                value,
            )

            if match:
                reference = match.group(1)

                if reference not in self._results:
                    raise KeyError(
                        (
                            "Unresolved step reference: "
                            f"{reference}"
                        )
                    )

                return self._results[reference]

            return value

        if isinstance(value, list):
            return [
                self._resolve_value(item)
                for item in value
            ]

        if isinstance(value, dict):
            return {
                key: self._resolve_value(item)
                for key, item in value.items()
            }

        return value

    def _run_step(
        self,
        step: Step,
        context: ToolContext,
    ) -> None:
        with self._lock:
            step.status = Status.RUNNING
            step.started_at = time.monotonic()

        self._emit(
            "step_started",
            step.description,
            {
                "step_id": step.id,
                "tool": step.tool,
            },
        )

        try:
            args = self._resolve_value(
                step.args
            )

        except KeyError as exc:
            result = ToolResult.failure(
                str(exc),
                retryable=False,
            )

            with self._lock:
                step.result = result
                step.status = Status.FAILED
                step.ended_at = time.monotonic()

            self._emit(
                "step_failed",
                str(exc),
                {
                    "step_id": step.id,
                },
            )

            return

        tool = self.tools[step.tool]
        max_attempts = step.max_retries + 1

        for attempt in range(
            1,
            max_attempts + 1,
        ):
            step.attempts = attempt

            try:
                result = tool(
                    args,
                    context,
                )

                if not isinstance(
                    result,
                    ToolResult,
                ):
                    raise TypeError(
                        (
                            f"Tool {step.tool!r} returned "
                            f"{type(result).__name__}; "
                            "expected ToolResult"
                        )
                    )

            except Exception as exc:
                result = ToolResult.failure(
                    (
                        "Unhandled tool exception: "
                        f"{type(exc).__name__}: {exc}"
                    ),
                    retryable=False,
                )

            if result.ok:
                with self._lock:
                    step.result = result
                    step.status = Status.DONE
                    step.ended_at = time.monotonic()

                    self._results[step.id] = (
                        result.data
                    )

                self.memory.store(
                    self._run_id,
                    f"step:{step.id}",
                    {
                        "tool": step.tool,
                        "confidence": result.confidence,
                        "metadata": result.metadata,
                        "data": result.data,
                    },
                )

                self._emit(
                    "step_completed",
                    step.description,
                    {
                        "step_id": step.id,
                        "attempt": attempt,
                        "confidence": (
                            result.confidence
                        ),
                    },
                )

                return

            can_retry = bool(
                result.retryable
                and attempt < max_attempts
            )

            self._emit(
                "step_attempt_failed",
                (
                    result.error
                    or "Tool failed"
                ),
                {
                    "step_id": step.id,
                    "attempt": attempt,
                    "retrying": can_retry,
                },
            )

            if can_retry:
                delay = (
                    self.retry_base_seconds
                    * (2 ** (attempt - 1))
                )

                delay += random.uniform(
                    0.0,
                    (
                        self.retry_base_seconds
                        * 0.2
                    ),
                )

                time.sleep(delay)
                continue

            with self._lock:
                step.result = result
                step.status = Status.FAILED
                step.ended_at = time.monotonic()

            self._emit(
                "step_failed",
                (
                    result.error
                    or "Tool failed"
                ),
                {
                    "step_id": step.id,
                    "attempts": attempt,
                },
            )

            return

    def _block_dependents(
        self,
    ) -> bool:
        changed = False

        by_id = {
            step.id: step
            for step in self.plan_steps
        }

        for step in self.plan_steps:
            if step.status != Status.PENDING:
                continue

            failed_dependencies = [
                dependency
                for dependency in step.depends_on
                if by_id[dependency].status
                in {
                    Status.FAILED,
                    Status.BLOCKED,
                }
            ]

            if not failed_dependencies:
                continue

            step.status = Status.BLOCKED

            step.result = ToolResult.failure(
                (
                    "Blocked by failed dependencies: "
                    + ", ".join(
                        failed_dependencies
                    )
                )
            )

            changed = True

            self._emit(
                "step_blocked",
                (
                    step.result.error
                    or "Step blocked"
                ),
                {
                    "step_id": step.id,
                    "dependencies": (
                        failed_dependencies
                    ),
                },
            )

        return changed

    def _dependency_status(
        self,
        dependency_id: str,
    ) -> Status:
        for step in self.plan_steps:
            if step.id == dependency_id:
                return step.status

        raise KeyError(
            (
                "Dependency does not exist: "
                f"{dependency_id}"
            )
        )

    def execute(self) -> bool:
        if not self.goal:
            raise RuntimeError(
                (
                    "No goal exists. "
                    "Call plan(objective) first."
                )
            )

        if not self.plan_steps:
            raise RuntimeError(
                (
                    "No plan exists. "
                    "Call plan(objective) first."
                )
            )

        self.validate_plan()

        self._run_id = uuid.uuid4().hex
        self._results = {}
        self._events = []
        self.last_report = None

        for step in self.plan_steps:
            step.status = Status.PENDING
            step.result = None
            step.attempts = 0
            step.started_at = None
            step.ended_at = None

        started_wall = dt.datetime.now(
            dt.timezone.utc
        )

        started_monotonic = time.monotonic()

        context = ToolContext(
            run_id=self._run_id,
            goal=self.goal,
            memory=self.memory,
            llm=self.llm,
            emit=self._emit,
        )

        self._emit(
            "run_started",
            (
                f"Executing "
                f"{len(self.plan_steps)} steps"
            ),
            {
                "run_id": self._run_id,
                "goal": self.goal,
            },
        )

        while True:
            self._block_dependents()

            ready = [
                step
                for step in self.plan_steps
                if (
                    step.status
                    == Status.PENDING
                )
                and all(
                    (
                        self._dependency_status(
                            dependency
                        )
                        == Status.DONE
                    )
                    for dependency
                    in step.depends_on
                )
            ]

            if not ready:
                terminal = all(
                    step.status
                    in {
                        Status.DONE,
                        Status.FAILED,
                        Status.BLOCKED,
                    }
                    for step in self.plan_steps
                )

                if terminal:
                    break

                pending = [
                    step.id
                    for step in self.plan_steps
                    if (
                        step.status
                        == Status.PENDING
                    )
                ]

                for step in self.plan_steps:
                    if (
                        step.status
                        == Status.PENDING
                    ):
                        step.status = Status.BLOCKED

                        step.result = ToolResult.failure(
                            "Scheduler made no progress"
                        )

                self._emit(
                    "scheduler_stalled",
                    "No runnable steps remained",
                    {
                        "pending": pending,
                    },
                )

                break

            batch = ready[
                :self.max_parallel
            ]

            with ThreadPoolExecutor(
                max_workers=len(batch)
            ) as pool:
                futures = [
                    pool.submit(
                        self._run_step,
                        step,
                        context,
                    )
                    for step in batch
                ]

                for future in as_completed(
                    futures
                ):
                    future.result()

        ended_wall = dt.datetime.now(
            dt.timezone.utc
        )

        elapsed = (
            time.monotonic()
            - started_monotonic
        )

        final_step = next(
            step
            for step in self.plan_steps
            if step.is_final
        )

        if (
            final_step.status == Status.DONE
            and final_step.result is not None
        ):
            final_output = str(
                final_step.result.data
            )
        else:
            final_output = ""

        failed = [
            step
            for step in self.plan_steps
            if step.status == Status.FAILED
        ]

        blocked = [
            step
            for step in self.plan_steps
            if step.status == Status.BLOCKED
        ]

        verification_passed = bool(
            final_step.result
            and final_step.result.metadata.get(
                "verification_passed",
                False,
            )
        )

        success = bool(
            not failed
            and not blocked
            and final_step.status == Status.DONE
        )

        if (
            success
            and verification_passed
        ):
            health = "GOOD"

        elif final_step.status == Status.DONE:
            health = "DEGRADED"

        else:
            health = "FAILED"

        evidence: list[
            dict[str, Any]
        ] = []

        seen_evidence: set[
            tuple[Any, ...]
        ] = set()

        for step in self.plan_steps:
            if not step.result:
                continue

            for item in step.result.evidence:
                fingerprint = (
                    item.get("type"),
                    item.get("url"),
                    item.get("sha256"),
                    item.get("title"),
                )

                if fingerprint in seen_evidence:
                    continue

                seen_evidence.add(fingerprint)
                evidence.append(item)

        step_reports: list[
            dict[str, Any]
        ] = []

        for step in self.plan_steps:
            duration: Optional[float] = None

            if (
                step.started_at is not None
                and step.ended_at is not None
            ):
                duration = round(
                    (
                        step.ended_at
                        - step.started_at
                    ),
                    3,
                )

            step_reports.append(
                {
                    "id": step.id,
                    "description": (
                        step.description
                    ),
                    "tool": step.tool,
                    "status": (
                        step.status.value
                    ),
                    "attempts": step.attempts,
                    "confidence": (
                        step.result.confidence
                        if step.result
                        else 0.0
                    ),
                    "error": (
                        step.result.error
                        if step.result
                        else None
                    ),
                    "metadata": (
                        step.result.metadata
                        if step.result
                        else {}
                    ),
                    "duration_seconds": duration,
                }
            )

        self._emit(
            "run_completed",
            (
                "Run finished with "
                f"health={health}"
            ),
            {
                "success": success,
                "failed_steps": [
                    step.id
                    for step in failed
                ],
                "blocked_steps": [
                    step.id
                    for step in blocked
                ],
                "elapsed_seconds": round(
                    elapsed,
                    3,
                ),
            },
        )

        self.last_report = RunReport(
            run_id=self._run_id,
            goal=self.goal,
            success=success,
            health=health,
            final_output=final_output,
            started_at=(
                started_wall.isoformat()
            ),
            ended_at=(
                ended_wall.isoformat()
            ),
            elapsed_seconds=round(
                elapsed,
                3,
            ),
            steps=step_reports,
            events=list(self._events),
            evidence=evidence,
        )

        self.memory.store(
            self._run_id,
            "run_report",
            self.last_report.to_dict(),
        )

        return success


# =============================================================================
# CLI
# =============================================================================


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "NOVA evidence-oriented "
            "research agent MVP"
        )
    )

    parser.add_argument(
        "--goal",
        required=True,
        help="Research objective",
    )

    parser.add_argument(
        "--output",
        default="nova_report.md",
        help=(
            "Path for the final "
            "Markdown report"
        ),
    )

    parser.add_argument(
        "--summary-json",
        default="nova_run.json",
        help=(
            "Path for the machine-readable "
            "execution report"
        ),
    )

    parser.add_argument(
        "--memory-db",
        default=".nova_memory.sqlite3",
        help="SQLite memory path",
    )

    parser.add_argument(
        "--max-parallel",
        type=int,
        default=4,
        help=(
            "Maximum number of independent "
            "steps to execute concurrently"
        ),
    )

    parser.add_argument(
        "--plan-only",
        action="store_true",
        help=(
            "Generate and print the plan "
            "without executing it"
        ),
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help=(
            "Print operational execution logs"
        ),
    )

    return parser


def main(
    argv: Optional[list[str]] = None,
) -> int:
    args = _build_parser().parse_args(
        argv
    )

    logging.basicConfig(
        level=(
            logging.INFO
            if args.verbose
            else logging.WARNING
        ),
        format=(
            "%(asctime)s "
            "%(levelname)s "
            "%(message)s"
        ),
    )

    with AgenticAI(
        memory_path=args.memory_db,
        max_parallel=args.max_parallel,
    ) as agent:
        agent.plan(args.goal)

        if args.plan_only:
            plan_payload = [
                dataclasses.asdict(step)
                for step in agent.plan_steps
            ]

            print(
                json.dumps(
                    plan_payload,
                    indent=2,
                    default=str,
                )
            )

            return 0

        success = agent.execute()

        if agent.last_report is None:
            raise RuntimeError(
                "Execution ended without a run report"
            )

        output_path = Path(
            args.output
        )

        summary_path = Path(
            args.summary_json
        )

        output_path.write_text(
            agent.last_report.final_output,
            encoding="utf-8",
        )

        summary_path.write_text(
            json.dumps(
                agent.last_report.to_dict(),
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )

        print(
            json.dumps(
                {
                    "success": (
                        agent.last_report.success
                    ),
                    "health": (
                        agent.last_report.health
                    ),
                    "run_id": (
                        agent.last_report.run_id
                    ),
                    "report": str(
                        output_path.resolve()
                    ),
                    "run_summary": str(
                        summary_path.resolve()
                    ),
                },
                indent=2,
            )
        )

        return (
            0
            if success
            else 1
        )


if __name__ == "__main__":
    raise SystemExit(main())
