#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "audit");
const STRICT = process.argv.includes("--strict");
const SKIP_DIRS = new Set([
  ".git",
  ".nova-data",
  "node_modules",
  "dist",
  "coverage",
  ".next",
  ".turbo",
  ".cache",
  "audit",
]);
const TEXT_EXTENSIONS = new Set([
  ".ts", ".tsx", ".mts", ".cts", ".js", ".mjs", ".cjs", ".jsx",
  ".py", ".sh", ".bash", ".html", ".css", ".scss", ".json",
  ".jsonl", ".yaml", ".yml", ".toml", ".md", ".txt", ".sql",
  ".graphql", ".gql", ".xml", ".env.example",
]);
const SPECIAL_FILES = new Set([
  ".dockerignore",
  ".gitignore",
  ".npmrc",
  ".replit",
  ".replitignore",
  "Dockerfile",
  "Dockerfile.simple",
  "Procfile",
  "Makefile",
]);
const CODE_EXTENSIONS = new Set([
  ".ts", ".tsx", ".mts", ".cts", ".js", ".mjs", ".cjs", ".jsx",
  ".py", ".sh", ".bash",
]);
const STRUCTURED_EXTENSIONS = new Set([
  ".json", ".jsonl", ".yaml", ".yml", ".toml",
]);
const NATIVE_FENCE_EXTENSIONS = new Set([
  ...STRUCTURED_EXTENSIONS,
  ...CODE_EXTENSIONS,
  ".html",
  ".css",
  ".scss",
  ".xml",
]);

const pattern = (...parts) => new RegExp(parts.join(""), "g");
const insensitivePattern = (...parts) => new RegExp(parts.join(""), "gi");
const SECRET_PATTERNS = [
  ["github-token", pattern("\\b(?:github", "_pat_|gh", "p_)[A-Za-z0-9_-]{16,}")],
  ["openai-token", pattern("\\bsk", "-(?:proj-|service-)?[A-Za-z0-9_-]{20,}")],
  ["kimi-token", pattern("\\bsk", "-kimi-[A-Za-z0-9_-]{16,}")],
  ["render-token", pattern("\\brnd", "_[A-Za-z0-9_-]{16,}")],
  ["tavily-token", pattern("\\btvly", "-[A-Za-z0-9_-]{16,}")],
  ["firecrawl-token", pattern("\\bfc", "-[A-Za-z0-9_-]{16,}")],
  ["steel-token", pattern("\\bste", "-[A-Za-z0-9_-]{16,}")],
  ["resend-token", pattern("\\bre", "_[A-Za-z0-9_-]{16,}")],
  ["pinecone-token", pattern("\\bpcsk", "_[A-Za-z0-9_-]{16,}")],
  ["e2b-token", pattern("\\be2b", "_[A-Za-z0-9_-]{16,}")],
  ["scrapfly-token", pattern("\\bscp", "-live-[A-Za-z0-9_-]{16,}")],
  ["composio-token", pattern("\\b(?:a", "k_|oa", "k_)[A-Za-z0-9_-]{16,}")],
  [
    "credential-url",
    insensitivePattern(
      "\\b(?:postgres(?:ql)?|mysql|mongodb(?:\\+srv)?):\\/\\/",
      "[^:\\s\"'\\/]+:[^@\\s\"']+@",
    ),
  ],
  [
    "private-key",
    pattern("-----BEGIN ", "(?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
  ],
];
const ASSIGNMENT =
  /^\s*([A-Z][A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|DATABASE_URL))\s*=\s*(.+?)\s*$/;
const SAFE_ASSIGNMENT =
  /^(?:"?\$\{|"?\{env:|"?<|"?example|"?changeme|"?replace|"?proxy|"?redacted|"?none|"?null|"?"?$)/i;

function relative(file) {
  return path.relative(ROOT, file).split(path.sep).join("/");
}
function digest(buffer) {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}
function candidate(file) {
  const base = path.basename(file);
  return SPECIAL_FILES.has(base) || TEXT_EXTENSIONS.has(path.extname(base).toLowerCase());
}
function walk(directory, output = []) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.name === ".DS_Store") continue;
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(absolute, output);
    } else if (entry.isFile() && candidate(absolute)) {
      output.push(absolute);
    }
  }
  return output;
}
function generated(text, file) {
  const head = text.slice(0, 1_200);
  return (
    /DO NOT EDIT THIS FILE[\s\S]{0,120}generated/i.test(head) ||
    /generated file/i.test(head) ||
    /\.min\.js$/i.test(file)
  );
}
function role(file) {
  const name = relative(file);
  if (/\/routes\//.test(name)) return "http-route";
  if (/\/lib\//.test(name)) return "runtime-library";
  if (/worker|daemon|poll-events|server\.(?:js|mjs|ts)$/.test(name)) return "runtime-process";
  if (/build\.(?:js|mjs|ts)$|Dockerfile|railway\.json|fly\.toml|\.replit$/.test(name)) return "build-deploy";
  if (/public\/|index\.html$|\.css$/.test(name)) return "ui-runtime";
  if (/test|spec/.test(name)) return "test";
  if (/package\.json$|tsconfig|pnpm-workspace|\.npmrc$/.test(name)) return "package-config";
  if (/\.md$/.test(name)) return "documentation";
  return "source-config";
}
function imports(text) {
  const found = new Set();
  for (const expression of [
    /\bfrom\s+["']([^"']+)["']/g,
    /\bimport\s*["']([^"']+)["']/g,
    /\bimport\s*\(\s*["']([^"']+)["']\s*\)/g,
    /\brequire\s*\(\s*["']([^"']+)["']\s*\)/g,
  ]) {
    for (const match of text.matchAll(expression)) found.add(match[1]);
  }
  return [...found].sort();
}
function documentation(file) {
  const name = relative(file).toLowerCase();
  const extension = path.extname(name);
  return (
    extension === ".md" ||
    extension === ".txt" ||
    extension === ".example" ||
    name.startsWith("attached_assets/") ||
    name.includes("/references/") ||
    name.includes("/examples/") ||
    name.includes("/templates/")
  );
}
function placeholder(line) {
  return /(?:\.\.\.|<[^>]+>|your[_ -]|replace|changeme|placeholder|example|sample|dummy|test[-_]|\[redacted\]|\{env:|process\.env)/i.test(line);
}
function secretScan(text, file) {
  const findings = [];
  const warnings = [];
  const docs = documentation(file);
  const lines = text.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    for (const [kind, expression] of SECRET_PATTERNS) {
      expression.lastIndex = 0;
      if (!expression.test(line)) continue;
      const item = { path: relative(file), line: index + 1, kind };
      if (docs || placeholder(line)) warnings.push(item);
      else findings.push(item);
    }
    const assignment = ASSIGNMENT.exec(line);
    if (!assignment) continue;
    const value = assignment[2].trim();
    if (SAFE_ASSIGNMENT.test(value) || value.startsWith("process.env")) continue;
    warnings.push({
      path: relative(file),
      line: index + 1,
      kind: `credential-assignment:${assignment[1]}`,
    });
  }
  return { findings, warnings };
}
function jsonError(text, file) {
  try {
    JSON.parse(text);
    return null;
  } catch (error) {
    return {
      path: relative(file),
      check: "json-parse",
      message: error instanceof Error ? error.message : String(error),
    };
  }
}
function jsonlErrors(text, file) {
  const errors = [];
  for (const [index, line] of text.split(/\r?\n/).entries()) {
    if (!line.trim()) continue;
    try {
      JSON.parse(line);
    } catch (error) {
      errors.push({
        path: relative(file),
        check: "jsonl-parse",
        line: index + 1,
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }
  return errors;
}
function syntaxError(file) {
  const result = spawnSync(process.execPath, ["--check", file], {
    cwd: ROOT,
    encoding: "utf8",
    timeout: 30_000,
  });
  if (result.status === 0) return null;
  return {
    path: relative(file),
    check: "node-syntax",
    exitCode: result.status,
    message: String(result.stderr || result.stdout || "syntax check failed").slice(0, 2_000),
  };
}
function fenceError(text, file) {
  const extension = path.extname(file).toLowerCase();
  if (!NATIVE_FENCE_EXTENSIONS.has(extension)) return null;
  if (!text.trimStart().startsWith("```")) return null;
  return {
    path: relative(file),
    check: "markdown-fence-in-native-file",
    message: "Native-format file begins with a Markdown code fence.",
  };
}

fs.mkdirSync(OUT, { recursive: true });
const files = walk(ROOT).sort((left, right) => relative(left).localeCompare(relative(right)));
const records = [];
const errors = [];
const secretFindings = [];
const credentialExamples = [];

for (const file of files) {
  const buffer = fs.readFileSync(file);
  const text = buffer.toString("utf8");
  const extension = path.extname(file).toLowerCase();
  records.push({
    path: relative(file),
    bytes: buffer.length,
    lines: text === "" ? 0 : text.split(/\r?\n/).length,
    sha256: digest(buffer),
    extension: extension || path.basename(file),
    role: role(file),
    generated: generated(text, file),
    imports: CODE_EXTENSIONS.has(extension) ? imports(text) : [],
  });
  const fence = fenceError(text, file);
  if (fence) errors.push(fence);
  if (extension === ".json") {
    const error = jsonError(text, file);
    if (error) errors.push(error);
  } else if (extension === ".jsonl") {
    errors.push(...jsonlErrors(text, file));
  }
  if ([".js", ".mjs", ".cjs"].includes(extension)) {
    const error = syntaxError(file);
    if (error) errors.push(error);
  }
  const secrets = secretScan(text, file);
  secretFindings.push(...secrets.findings);
  credentialExamples.push(...secrets.warnings);
}

function counts(property) {
  return Object.fromEntries(
    [...new Set(records.map((record) => record[property]))]
      .sort()
      .map((value) => [value, records.filter((record) => record[property] === value).length]),
  );
}
const report = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  strict: STRICT,
  summary: {
    files: records.length,
    generatedFiles: records.filter((record) => record.generated).length,
    parseOrSyntaxErrors: errors.length,
    secretFindings: secretFindings.length,
    credentialExamples: credentialExamples.length,
    roleCounts: counts("role"),
    extensionCounts: counts("extension"),
  },
  files: records,
  errors,
  secretFindings,
  credentialExamples,
};

fs.writeFileSync(path.join(OUT, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
fs.writeFileSync(path.join(OUT, "source-files.txt"), `${records.map((record) => record.path).join("\n")}\n`);
fs.writeFileSync(path.join(OUT, "source-files.nul"), Buffer.from(`${records.map((record) => record.path).join("\0")}\0`));
fs.writeFileSync(
  path.join(OUT, "report.md"),
  [
    "# Repository Audit",
    "",
    `- Files inventoried: ${report.summary.files}`,
    `- Parse/syntax errors: ${report.summary.parseOrSyntaxErrors}`,
    `- High-confidence secret indicators: ${report.summary.secretFindings}`,
    `- Credential examples/warnings: ${report.summary.credentialExamples}`,
    "",
    "## Parse and syntax findings",
    "",
    ...(errors.length ? errors.map((error) => `- ${error.path}: ${error.check} — ${error.message}`) : ["- None"]),
    "",
    "## High-confidence secret indicators",
    "",
    ...(secretFindings.length ? secretFindings.map((item) => `- ${item.path}:${item.line} — ${item.kind} (redacted)`) : ["- None"]),
    "",
    "## Credential examples and warnings",
    "",
    ...(credentialExamples.length ? credentialExamples.map((item) => `- ${item.path}:${item.line} — ${item.kind} (example redacted)`) : ["- None"]),
    "",
    "## Inventory",
    "",
    ...records.map((record) => `- ${record.path} — ${record.role}; ${record.lines} lines; sha256 ${record.sha256}${record.generated ? "; generated" : ""}`),
    "",
  ].join("\n"),
);
console.log(JSON.stringify(report.summary, null, 2));
if (STRICT && (errors.length || secretFindings.length)) process.exitCode = 1;
