#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.cwd();
const OUT_DIR = path.join(ROOT, "audit");
const STRICT = process.argv.includes("--strict");

const EXCLUDED_DIRS = new Set([
  ".git",
  ".nova-data",
  "node_modules",
  "dist",
  "coverage",
  ".next",
  ".turbo",
  ".cache",
  "audit",
]);

const TEXT_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".js",
  ".mjs",
  ".cjs",
  ".jsx",
  ".py",
  ".sh",
  ".bash",
  ".html",
  ".css",
  ".scss",
  ".json",
  ".jsonl",
  ".yaml",
  ".yml",
  ".toml",
  ".md",
  ".txt",
  ".sql",
  ".graphql",
  ".gql",
  ".xml",
  ".env.example",
]);

const SPECIAL_TEXT_FILES = new Set([
  ".dockerignore",
  ".gitignore",
  ".npmrc",
  ".replit",
  ".replitignore",
  "Dockerfile",
  "Dockerfile.simple",
  "Procfile",
  "Makefile",
]);

const CODE_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".mts",
  ".cts",
  ".js",
  ".mjs",
  ".cjs",
  ".jsx",
  ".py",
  ".sh",
  ".bash",
]);

const STRUCTURED_EXTENSIONS = new Set([
  ".json",
  ".jsonl",
  ".yaml",
  ".yml",
  ".toml",
]);

const SECRET_SIGNATURES = [
  ["github-token", /\b(?:github_pat_|ghp_)[A-Za-z0-9_\-]{16,}/g],
  ["openai-token", /\bsk-(?:proj-|service-)?[A-Za-z0-9_\-]{20,}/g],
  ["kimi-token", /\bsk-kimi-[A-Za-z0-9_\-]{16,}/g],
  ["render-token", /\brnd_[A-Za-z0-9_\-]{16,}/g],
  ["tavily-token", /\btvly-[A-Za-z0-9_\-]{16,}/g],
  ["firecrawl-token", /\bfc-[A-Za-z0-9_\-]{16,}/g],
  ["steel-token", /\bste-[A-Za-z0-9_\-]{16,}/g],
  ["resend-token", /\bre_[A-Za-z0-9_\-]{16,}/g],
  ["pinecone-token", /\bpcsk_[A-Za-z0-9_\-]{16,}/g],
  ["e2b-token", /\be2b_[A-Za-z0-9_\-]{16,}/g],
  ["scrapfly-token", /\bscp-live-[A-Za-z0-9_\-]{16,}/g],
  ["composio-token", /\b(?:ak_|oak_)[A-Za-z0-9_\-]{16,}/g],
  ["generic-private-key", /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g],
];

const CREDENTIAL_ASSIGNMENT = /^\s*([A-Z][A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|DATABASE_URL))\s*=\s*(.+?)\s*$/;
const SAFE_ASSIGNMENT_VALUES = /^(?:"?\$\{|"?\{env:|"?<|"?example|"?changeme|"?replace|"?proxy|"?redacted|"?none|"?null|"?"?$)/i;

function sha256(buffer) {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}

function rel(file) {
  return path.relative(ROOT, file).split(path.sep).join("/");
}

function isTextCandidate(file) {
  const base = path.basename(file);
  const extension = path.extname(base).toLowerCase();
  return SPECIAL_TEXT_FILES.has(base) || TEXT_EXTENSIONS.has(extension);
}

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === ".DS_Store") continue;
    const absolute = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!EXCLUDED_DIRS.has(entry.name)) walk(absolute, files);
      continue;
    }
    if (entry.isFile() && isTextCandidate(absolute)) files.push(absolute);
  }
  return files;
}

function looksGenerated(text, filePath) {
  const head = text.slice(0, 1200);
  return (
    /DO NOT EDIT THIS FILE[\s\S]{0,120}generated/i.test(head) ||
    /generated file/i.test(head) ||
    /\.min\.js$/i.test(filePath)
  );
}

function runtimeRole(filePath) {
  const p = rel(filePath);
  if (/\/routes\//.test(p)) return "http-route";
  if (/\/lib\//.test(p)) return "runtime-library";
  if (/worker|daemon|poll-events|server\.(?:js|mjs|ts)$/.test(p)) return "runtime-process";
  if (/build\.(?:js|mjs|ts)$|Dockerfile|railway\.json|fly\.toml|\.replit$/.test(p)) return "build-deploy";
  if (/public\/|index\.html$|\.css$/.test(p)) return "ui-runtime";
  if (/test|spec/.test(p)) return "test";
  if (/package\.json$|tsconfig|pnpm-workspace|\.npmrc$/.test(p)) return "package-config";
  if (/\.md$/.test(p)) return "documentation";
  return "source-config";
}

function extractImports(text) {
  const imports = new Set();
  const patterns = [
    /\bfrom\s+["']([^"']+)["']/g,
    /\bimport\s*["']([^"']+)["']/g,
    /\bimport\s*\(\s*["']([^"']+)["']\s*\)/g,
    /\brequire\s*\(\s*["']([^"']+)["']\s*\)/g,
  ];
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) imports.add(match[1]);
  }
  return [...imports].sort();
}

function scanSecrets(text, filePath) {
  const findings = [];
  const lines = text.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    for (const [kind, pattern] of SECRET_SIGNATURES) {
      pattern.lastIndex = 0;
      if (pattern.test(line)) {
        findings.push({ path: rel(filePath), line: index + 1, kind });
      }
    }
    const assignment = CREDENTIAL_ASSIGNMENT.exec(line);
    if (assignment) {
      const value = assignment[2].trim();
      if (!SAFE_ASSIGNMENT_VALUES.test(value) && !value.startsWith("process.env")) {
        findings.push({
          path: rel(filePath),
          line: index + 1,
          kind: `credential-assignment:${assignment[1]}`,
        });
      }
    }
  }
  return findings;
}

function parseJson(text, filePath) {
  try {
    JSON.parse(text);
    return null;
  } catch (error) {
    return {
      path: rel(filePath),
      check: "json-parse",
      message: error instanceof Error ? error.message : String(error),
    };
  }
}

function parseJsonLines(text, filePath) {
  const errors = [];
  const lines = text.split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    if (!lines[index].trim()) continue;
    try {
      JSON.parse(lines[index]);
    } catch (error) {
      errors.push({
        path: rel(filePath),
        check: "jsonl-parse",
        line: index + 1,
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }
  return errors;
}

function nodeSyntaxCheck(filePath) {
  const result = spawnSync(process.execPath, ["--check", filePath], {
    cwd: ROOT,
    encoding: "utf8",
    timeout: 30_000,
  });
  if (result.status === 0) return null;
  return {
    path: rel(filePath),
    check: "node-syntax",
    exitCode: result.status,
    message: String(result.stderr || result.stdout || "syntax check failed").slice(0, 2000),
  };
}

function markdownFenceMismatch(text, filePath) {
  const extension = path.extname(filePath).toLowerCase();
  if (extension === ".md") return null;
  const first = text.trimStart().slice(0, 12);
  if (first.startsWith("```")) {
    return {
      path: rel(filePath),
      check: "markdown-fence-in-native-file",
      message: "Native-format file begins with a Markdown code fence.",
    };
  }
  return null;
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const files = walk(ROOT).sort((a, b) => rel(a).localeCompare(rel(b)));
const records = [];
const errors = [];
const secretFindings = [];

for (const filePath of files) {
  const buffer = fs.readFileSync(filePath);
  const text = buffer.toString("utf8");
  const extension = path.extname(filePath).toLowerCase();
  const record = {
    path: rel(filePath),
    bytes: buffer.length,
    lines: text === "" ? 0 : text.split(/\r?\n/).length,
    sha256: sha256(buffer),
    extension: extension || path.basename(filePath),
    role: runtimeRole(filePath),
    generated: looksGenerated(text, filePath),
    imports: CODE_EXTENSIONS.has(extension) ? extractImports(text) : [],
  };
  records.push(record);

  const fenceError = markdownFenceMismatch(text, filePath);
  if (fenceError) errors.push(fenceError);

  if (extension === ".json") {
    const jsonError = parseJson(text, filePath);
    if (jsonError) errors.push(jsonError);
  } else if (extension === ".jsonl") {
    errors.push(...parseJsonLines(text, filePath));
  }

  if ([".js", ".mjs", ".cjs"].includes(extension)) {
    const syntaxError = nodeSyntaxCheck(filePath);
    if (syntaxError) errors.push(syntaxError);
  }

  secretFindings.push(...scanSecrets(text, filePath));
}

const roleCounts = Object.fromEntries(
  [...new Set(records.map((record) => record.role))]
    .sort()
    .map((role) => [role, records.filter((record) => record.role === role).length]),
);

const extensionCounts = Object.fromEntries(
  [...new Set(records.map((record) => record.extension))]
    .sort()
    .map((extension) => [
      extension,
      records.filter((record) => record.extension === extension).length,
    ]),
);

const report = {
  schemaVersion: 1,
  generatedAt: new Date().toISOString(),
  root: ".",
  strict: STRICT,
  summary: {
    files: records.length,
    generatedFiles: records.filter((record) => record.generated).length,
    parseOrSyntaxErrors: errors.length,
    secretFindings: secretFindings.length,
    roleCounts,
    extensionCounts,
  },
  files: records,
  errors,
  secretFindings,
};

fs.writeFileSync(path.join(OUT_DIR, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
fs.writeFileSync(
  path.join(OUT_DIR, "source-files.txt"),
  `${records.map((record) => record.path).join("\n")}\n`,
);
fs.writeFileSync(
  path.join(OUT_DIR, "source-files.nul"),
  Buffer.from(`${records.map((record) => record.path).join("\0")}\0`, "utf8"),
);

const markdown = [
  "# Repository Audit",
  "",
  `- Files inventoried: ${report.summary.files}`,
  `- Generated files identified: ${report.summary.generatedFiles}`,
  `- Parse/syntax errors: ${report.summary.parseOrSyntaxErrors}`,
  `- Secret indicators: ${report.summary.secretFindings}`,
  "",
  "## Role counts",
  "",
  ...Object.entries(roleCounts).map(([role, count]) => `- ${role}: ${count}`),
  "",
  "## Parse and syntax findings",
  "",
  ...(errors.length
    ? errors.map((error) => `- ${error.path}: ${error.check} — ${error.message}`)
    : ["- None"]),
  "",
  "## Secret indicators",
  "",
  ...(secretFindings.length
    ? secretFindings.map(
        (finding) => `- ${finding.path}:${finding.line} — ${finding.kind} (value redacted)`,
      )
    : ["- None"]),
  "",
  "## Inventory",
  "",
  ...records.map(
    (record) =>
      `- ${record.path} — ${record.role}; ${record.lines} lines; sha256 ${record.sha256}${record.generated ? "; generated" : ""}`,
  ),
  "",
].join("\n");

fs.writeFileSync(path.join(OUT_DIR, "report.md"), markdown);
console.log(JSON.stringify(report.summary, null, 2));

if (STRICT && (errors.length > 0 || secretFindings.length > 0)) {
  process.exitCode = 1;
}
